export const ACTIONS = {
  INCREASE_NUMBER_1: 'INCREASE_NUMBER_1',
  DECREASE_NUMBER_1: 'DECREASE_NUMBER_1',
  FETCH_SMILE: 'FETCH_SMILE',
  FETCH_SMILE_SUCCEEDED: 'FETCH_SMILE_SUCCEEDED',
  FETCH_SMILE_STARTED: 'FETCH_SMILE_STARTED',
  FETCH_SMILE_FAILED: 'FETCH_SMILE_FAILED',
  FETCH_TIMER_STARTED: 'FETCH_TIMER_STARTED',
  FETCH_TIMER_INCREMENT: 'FETCH_TIMER_INCREMENT',
  FETCH_TIMER_RESET: 'FETCH_TIMER_RESET',
}